In [1]:
import numpy as np

# Creating arrays

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
a = np.array([1,2,3,4,5],dtype="float")

In [6]:
a

array([1., 2., 3., 4., 5.])

In [9]:
a = np.array([1+3j,2,3,4,5],dtype="complex")

In [10]:
a

array([1.+3.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

# Properties of array

In [11]:
a = np.array([10,20,30,40])

In [12]:
a.dtype

dtype('int32')

In [13]:
a.ndim

1

In [14]:
a.shape

(4,)

In [15]:
a.size

4

In [16]:
a.itemsize

4

In [17]:
a = np.array([1,2.5,"a"])

In [18]:
a

array(['1', '2.5', 'a'], dtype='<U32')

In [19]:
a.dtype

dtype('<U32')

In [20]:
a = np.array([[1,2,3],[4,5,6]])

In [21]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
a.dtype

dtype('int32')

In [23]:
a.ndim

2

In [24]:
a.shape

(2, 3)

In [25]:
a.itemsize

4

# Different Ways of Creating Arrays

In [27]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [28]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
#Multi dimension

np.arange(30).reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [34]:
np.arange(1,31,2).reshape(3,5,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]],

       [[21],
        [23],
        [25],
        [27],
        [29]]])

In [35]:
# Using random numbers

np.random.randn(30).reshape(3,5,2)

array([[[-1.67790584, -0.89143534],
        [-0.63067426,  0.92936982],
        [ 0.42480756,  0.01722123],
        [ 0.86047952,  1.02707507],
        [ 0.17022449,  1.06360476]],

       [[-2.50442572,  2.63345316],
        [ 0.83688754, -1.11805902],
        [-1.9960293 ,  1.40679794],
        [-2.05768115, -0.08526822],
        [ 1.22268275,  1.59813045]],

       [[ 1.04683668,  0.53310105],
        [-0.11778919,  0.13373795],
        [-0.34448925, -1.30795096],
        [-1.0176148 , -0.66747567],
        [-0.68696669, -0.62598554]]])

In [36]:
np.random.randn(15).reshape(3,5)

array([[ 0.5257611 ,  0.29733471, -0.17406488, -0.17247741, -0.11537139],
       [ 0.44155331, -1.37015979,  0.97494297,  1.87137   ,  0.61568269],
       [-0.0887352 , -0.23689639,  0.1002013 , -0.31218369,  0.51407673]])

In [38]:
np.linspace(2,11,5)

array([ 2.  ,  4.25,  6.5 ,  8.75, 11.  ])

In [39]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [40]:
np.logspace(10,20,5)

array([1.00000000e+10, 3.16227766e+12, 1.00000000e+15, 3.16227766e+17,
       1.00000000e+20])

In [43]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [44]:
np.ones(4)

array([1., 1., 1., 1.])

In [45]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

# Aggregate functions

In [47]:
a = np.array([[10,20,11],[12,9,7]])

In [48]:
a

array([[10, 20, 11],
       [12,  9,  7]])

In [49]:
a.max()

20

In [50]:
a.max(axis=0)

array([12, 20, 11])

In [51]:
a.max(axis=1)

array([20, 12])

In [52]:
a.min()

7

In [53]:
a.sum()

69

In [55]:
a = np.array([[[1,2],[3,4]],[[9,7],[6,8]],[[5,1],[3,2]]])

In [56]:
a

array([[[1, 2],
        [3, 4]],

       [[9, 7],
        [6, 8]],

       [[5, 1],
        [3, 2]]])

In [57]:
a.max(axis=0)

array([[9, 7],
       [6, 8]])

In [58]:
a.max(axis=1)

array([[3, 4],
       [9, 8],
       [5, 2]])

In [59]:
a.max(axis=2)

array([[2, 4],
       [9, 8],
       [5, 3]])

In [60]:
a.mean()

4.25

In [61]:
a.var()

6.854166666666667

In [62]:
a.std()

2.6180463454008347

# Numpy functions

In [74]:
a1 = np.arange(10,18).reshape(2,4)
a2 = np.arange(8).reshape(2,4)

In [75]:
a1

array([[10, 11, 12, 13],
       [14, 15, 16, 17]])

In [76]:
a2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [77]:
np.concatenate([a1,a2])

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [78]:
np.concatenate((a1,a2),axis=0)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [79]:
np.concatenate((a1,a2),axis=1)

array([[10, 11, 12, 13,  0,  1,  2,  3],
       [14, 15, 16, 17,  4,  5,  6,  7]])

In [80]:
a = np.array([1,1,2,2,2,3,3,4,4,4,4])

np.unique(a)

array([1, 2, 3, 4])

In [82]:
 l = [['rcb','kkr','rcb','kkr'],['mi','rr','srh','dd']]

In [83]:
l

[['rcb', 'kkr', 'rcb', 'kkr'], ['mi', 'rr', 'srh', 'dd']]

In [84]:
a = np.array(l)

In [85]:
a

array([['rcb', 'kkr', 'rcb', 'kkr'],
       ['mi', 'rr', 'srh', 'dd']], dtype='<U3')

In [86]:
np.unique(a)

array(['dd', 'kkr', 'mi', 'rcb', 'rr', 'srh'], dtype='<U3')

# Indexing and Slicing

In [88]:
a = np.arange(20).reshape(4,5)

In [89]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [90]:
a[1]

array([5, 6, 7, 8, 9])

In [91]:
a[1][4]

9

In [92]:
a[1,4]

9

In [93]:
a[3]

array([15, 16, 17, 18, 19])

In [94]:
a[3][1:4]

array([16, 17, 18])

In [95]:
a[3,1:4]

array([16, 17, 18])

In [96]:
a[:2,2:]

array([[2, 3, 4],
       [7, 8, 9]])

In [104]:
# Multi-selector
a[[1,3,2],[2,3,4]]

array([ 7, 18, 14])

# Vectorization

In [105]:
a = np.array([1,2,3])

In [106]:
a

array([1, 2, 3])

In [107]:
a+2

array([3, 4, 5])

In [108]:
a*10

array([10, 20, 30])

In [110]:
a>2

array([False, False,  True])

# Broadcasting

In [111]:
a1 = np.array([1,2,3])
a2 = np.arange(1,4).reshape(3,1)

In [112]:
a1

array([1, 2, 3])

In [113]:
a2

array([[1],
       [2],
       [3]])

In [114]:
a1+a2

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

# Boolean indexing

In [116]:
a = np.array([1,2,3,4,5,6,8])

In [117]:
a

array([1, 2, 3, 4, 5, 6, 8])

In [119]:
a[a>5]

array([6, 8])

In [120]:
a[a%2==0]

array([2, 4, 6, 8])

# ====================================

In [121]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [122]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
a.mean()

5.0

In [124]:
a.mean(axis=0)

array([4., 5., 6.])

In [125]:
a.mean(axis=1)

array([2., 5., 8.])

In [131]:
a[2].mean()

8.0

In [133]:
a[:,2].mean()

6.0

In [135]:
a[:,2]

array([3, 6, 9])